// Generated by scripts/build-seed.ts from data/*.csv — do not edit by hand.
// Regenerate with: bun run packages/catalog/scripts/build-seed.ts
import type {Catalog, SourceRegister} from './schema';

export const sourceRegister: SourceRegister = [
  {
    "id": "R01",
    "class": "User direction",
    "source": "Current request",
    "applied_to": "Kulhad split, laser-marked Terre, mixed-material Forge, strip/serrated knife concepts",
    "boundary": "Concept direction; not a verified product claim."
  },
  {
    "id": "R02",
    "class": "Reference brand",
    "source": "Made In craftsmanship and collection architecture",
    "url": "https://made-in-cookware.com/craftsmanship",
    "applied_to": "Material-led line logic, professional tool classes, maker/process narrative",
    "boundary": "Reference class only; no Made In specification is attributed to Maison Tavo."
  },
  {
    "id": "R03",
    "class": "Reference brand",
    "source": "Made In Complete Kitchen Set",
    "url": "https://madeincookware.com/products/the-stainless-sets/curated-kitchen",
    "applied_to": "Cookware + knives + tabletop breadth",
    "boundary": "Used to shape catalogue adjacency, not copy products."
  },
  {
    "id": "R04",
    "class": "Process reference",
    "source": "Ceramic laser engraving guide",
    "url": "https://www.thunderlaser.com/material-application/ceramic.html",
    "applied_to": "Laser-marked Terre concepts",
    "boundary": "Confirms feasibility classes only; actual glaze/process settings require testing."
  },
  {
    "id": "R05",
    "class": "Product reference",
    "source": "Removable ceramic insert travel mug",
    "url": "https://roamwildproducts.co.uk/products/roamwild-cerami-travel-mug",
    "applied_to": "Replaceable mixed-material kulhad architecture",
    "boundary": "Reference proves removable insert class, not Maison Tavo performance."
  },
  {
    "id": "R06",
    "class": "Knife reference",
    "source": "Dexter scalloped cook’s knife",
    "url": "https://dexter1818.com/sani-safe-scalloped-cook-s-knife/",
    "applied_to": "Chef-format serrated reference class",
    "boundary": "Supports use-class; Maison Tavo geometry remains speculative."
  },
  {
    "id": "R07",
    "class": "Knife reference",
    "source": "Kyocera micro-serrated knives",
    "url": "https://cutlery.kyocera.com/",
    "applied_to": "Fine serration task logic",
    "boundary": "Ceramic blade reference only; proposed Maison Tavo blades are metal."
  },
  {
    "id": "R08",
    "class": "Shopify",
    "source": "Product CSV guide",
    "url": "https://help.shopify.com/en/manual/products/import-export/using-csv",
    "applied_to": "Import structure and product-level fields",
    "boundary": "Template headers preserved exactly."
  },
  {
    "id": "R09",
    "class": "Shopify",
    "source": "Standard Product Taxonomy",
    "url": "https://shopify.github.io/product-taxonomy/releases/2026-08/",
    "applied_to": "Product category breadcrumbs",
    "boundary": "Categories verified against current public taxonomy."
  }
];

export const seedCatalog: Catalog = [
  {
    "handle": "ardh-metal-lined-kulhad",
    "title": "Ardh Metal-Lined Kulhad",
    "sku": "MT-TER-KUL-140",
    "vendor": "Maison Tavo",
    "product_category": "Home & Garden > Kitchen & Dining > Tableware > Drinkware > Mugs",
    "product_type": "Kulhad",
    "tags": [
      "Terre Clay",
      "Kulhad",
      "Chai",
      "Earthenware",
      "Stainless Steel",
      "Mixed Material",
      "Hospitality",
      "Concept Spec"
    ],
    "lineup": "Terre Clay",
    "status": "draft",
    "claim_status": "CONCEPT_SPEC",
    "reference_class": "hybrid hospitality drinkware",
    "concept_thesis": "Separate expressive shell from hygienic drink interface.",
    "material_architecture": "Lower high-fired earthenware shell + removable thin 18/8 stainless liner + isolated junction.",
    "food_contact_strategy": "Stainless liner is the intended food-contact surface; rim must avoid exposed adhesive or moisture traps.",
    "fabrication_route": "Slip-cast or press-mould shell; drawn/spun liner; dry seat or food-safe isolation ring; laser mark only after glaze trials.",
    "interaction_performance_intent": "140 ml chai portion, stackable only if liner/rim geometry protects clay, replaceable insert.",
    "care_hypothesis": "Separate components; hand wash initial prototype.",
    "engineering_risks": [
      "Differential thermal expansion",
      "trapped moisture",
      "hot rim",
      "clay chipping",
      "crevice hygiene."
    ],
    "required_prototype_tests": [
      "Thermal cycling",
      "hot-fill",
      "rim temperature",
      "drop",
      "liner extraction",
      "migration",
      "commercial wash",
      "crevice cleanability."
    ],
    "agent_intents": [
      "chai service",
      "reusable kulhad",
      "mixed-material cup",
      "tasting vessel"
    ],
    "negative_constraints": [
      "microwave use",
      "guaranteed dishwasher safe",
      "disposable earthenware"
    ],
    "benchmark_logic": "Hybrid cup references prove mixed ceramic/metal systems, but this inverted architecture needs original testing.",
    "sources": [
      "R01",
      "R02",
      "R05"
    ],
    "description_html": "<p>A reusable kulhad concept that keeps the tactile irregularity of fired clay while introducing a removable stainless-steel liner at the drink interface.</p><h3>Material split</h3><p>The upper drinking vessel is a thin 18/8 stainless insert. A high-fired earthenware lower shell creates grip, visual weight and the familiar flared kulhad silhouette. The two materials meet below the lip so the mouth contacts polished steel rather than a brittle clay edge.</p><h3>Why it exists</h3><p>The insert can be removed for cleaning or replacement while the clay shell remains the expressive object. A dry mechanical seat, high-temperature silicone isolation ring or other food-safe decoupling method should be tested rather than permanently bonding materials with different thermal expansion.</p><h3>Service mode</h3><p>Designed as a compact 140 ml chai cup for table service, tasting menus and hospitality sets. The metal half is the hygienic, repeatable component; the earthenware half carries variation and provenance.</p><p><strong>Concept-spec notice:</strong> Capacity, food-contact materials, joint system, drop resistance, glaze migration, thermal shock and dishwasher performance are unverified prototype targets.</p>",
    "seo_title": "Ardh Metal-Lined Kulhad | Maison Tavo",
    "seo_description": "A half-earthenware, half-stainless reusable kulhad concept for chai service, structured as a removable material system.",
    "price_usd": 48,
    "weight_grams": 210,
    "variant_option": {
      "name": "Capacity",
      "value": "140 ml"
    },
    "dimensions": {
      "capacity_ml": 140
    },
    "heat_sources": [],
    "induction_compatible": false
  },
  {
    "handle": "ardh-clay-lined-kulhad",
    "title": "Ardh Clay-Lined Kulhad",
    "sku": "MT-TER-KUL-C180",
    "vendor": "Maison Tavo",
    "product_category": "Home & Garden > Kitchen & Dining > Tableware > Drinkware > Mugs",
    "product_type": "Kulhad",
    "tags": [
      "Terre Clay",
      "Kulhad",
      "Chai",
      "Earthenware",
      "Stainless Steel",
      "Modular",
      "Hospitality",
      "Concept Spec"
    ],
    "lineup": "Terre Clay",
    "status": "draft",
    "claim_status": "CONCEPT_SPEC",
    "reference_class": "modular hospitality drinkware",
    "concept_thesis": "Make breakage replaceable while preserving a clay lip and beverage surface.",
    "material_architecture": "Glazed/vitrified earthenware upper bowl + spun stainless lower chassis + reversible retained joint.",
    "food_contact_strategy": "Clay/glaze contacts beverage; metal is external support.",
    "fabrication_route": "High-fire clay insert; spun metal chassis; gasket or captive mechanical ring; inspect joint for drainage.",
    "interaction_performance_intent": "180 ml chai/lassi tasting service; replaceable clay insert; stable weighted base.",
    "care_hypothesis": "Disassemble to wash; no microwave; dishwasher only after validation.",
    "engineering_risks": [
      "Glaze migration",
      "chip at waist",
      "water ingress",
      "retention failure",
      "thermal expansion."
    ],
    "required_prototype_tests": [
      "Lead/cadmium migration",
      "thermal shock",
      "component pull-out",
      "drop",
      "500 wash cycles",
      "drainage and drying."
    ],
    "agent_intents": [
      "clay-lined cup",
      "replacement insert",
      "chai service",
      "modular drinkware"
    ],
    "negative_constraints": [
      "microwave safe",
      "monolithic cup",
      "disposable kulhad"
    ],
    "benchmark_logic": "Reference class: removable ceramic insert travelware, translated into a low, handleless hospitality format.",
    "sources": [
      "R01",
      "R02",
      "R05"
    ],
    "description_html": "<p>A reusable kulhad concept with a food-contact clay bowl suspended inside a protective metal lower chassis, preserving the clay drinking experience while making the base serviceable.</p><h3>Material split</h3><p>A glazed or vitrified earthenware upper bowl forms the entire lip and beverage surface. A spun stainless lower half wraps the vulnerable foot and provides a stable service base.</p><h3>Replaceable body</h3><p>The clay insert is conceived as replaceable after breakage, while the metal base remains in circulation. The connection should be reversible and visually expressed as a precise waist rather than disguised as a monolithic cup.</p><h3>Hospitality logic</h3><p>The product turns breakage into a component event instead of total product loss, creating a parts-led service model suitable for restaurants and tea programmes.</p><p><strong>Concept-spec notice:</strong> The vessel is not microwave-safe because of the metal base. Joint retention, glaze safety, washability and thermal performance require testing.</p>",
    "seo_title": "Ardh Clay-Lined Kulhad | Maison Tavo",
    "seo_description": "A modular kulhad concept with a clay drinking bowl seated inside a reusable stainless lower chassis.",
    "price_usd": 58,
    "weight_grams": 260,
    "variant_option": {
      "name": "Capacity",
      "value": "180 ml"
    },
    "dimensions": {
      "capacity_ml": 180
    },
    "heat_sources": [],
    "induction_compatible": false
  },
  {
    "handle": "rekha-laser-marked-serving-platter",
    "title": "Rekhā Laser-Marked Serving Platter",
    "sku": "MT-TER-PLT-34",
    "vendor": "Maison Tavo",
    "product_category": "Home & Garden > Kitchen & Dining > Tableware > Serveware > Serving Platters",
    "product_type": "Serving platter",
    "tags": [
      "Terre Clay",
      "Serving Platter",
      "Laser Marked",
      "Ceramic",
      "Hospitality",
      "Concept Spec"
    ],
    "lineup": "Terre Clay",
    "status": "draft",
    "claim_status": "CONCEPT_SPEC",
    "reference_class": "laser-marked ceramic tabletop",
    "concept_thesis": "Use laser marking as permanent ornament, identity and provenance layer.",
    "material_architecture": "High-fired stoneware body; tested glaze field; unmarked food-contact zone until validated.",
    "food_contact_strategy": "Glaze/body must pass migration and cleanability testing after marking.",
    "fabrication_route": "Create flat and curved coupons across glaze variants; map power/speed; inspect under magnification; wash-cycle before vessel trial.",
    "interaction_performance_intent": "34 cm shared-service platter; low rim; pattern remains tactile but cleanable.",
    "care_hypothesis": "Non-abrasive wash; commercial dishwasher status pending.",
    "engineering_risks": [
      "Micro-cracks",
      "glaze flaking",
      "stain capture",
      "inconsistent contrast",
      "curvature focus error."
    ],
    "required_prototype_tests": [
      "Microscopy",
      "dye penetrant",
      "cutlery abrasion",
      "500 wash cycles",
      "stain",
      "lead/cadmium migration post-marking."
    ],
    "agent_intents": [
      "laser-etched platter",
      "ceramic serveware",
      "provenance-marked tableware"
    ],
    "negative_constraints": [
      "assumed dishwasher safe",
      "deep engraving on food surface"
    ],
    "benchmark_logic": "Ceramic marking is feasible, but laser settings are glaze-specific and cannot be copied as universal production parameters.",
    "sources": [
      "R01",
      "R02",
      "R04"
    ],
    "description_html": "<p>A high-fired serving platter whose decoration is generated by selectively laser-marking a tested ceramic surface instead of printing a surface graphic.</p><h3>Laser field</h3><p>A radial contour map moves from dense micro-lines at the centre to wider spacing at the rim. The pattern can encode batch, maker or recipe data while remaining visually quiet.</p><h3>Surface strategy</h3><p>Two development routes are preserved: mark a compatible glaze to create tonal contrast, or engrave a controlled unglazed exterior zone. The food-contact face should not be deeply ablated until cleanability and glaze integrity are proven.</p><h3>Service use</h3><p>The 34 cm format is intended for bread, shared dishes and tableside plating. A broad low profile makes the laser pattern legible at rest.</p><p><strong>Concept-spec notice:</strong> Laser wavelength, power, mark depth, glaze chemistry, micro-cracking, stain resistance and food-contact suitability require coupon tests before product use.</p>",
    "seo_title": "Rekhā Laser-Marked Platter | Maison Tavo",
    "seo_description": "A 34 cm high-fired ceramic serving platter concept with a tested laser-marked contour pattern and structured provenance.",
    "price_usd": 145,
    "weight_grams": 1750,
    "variant_option": {
      "name": "Diameter",
      "value": "34 cm"
    },
    "dimensions": {
      "diameter_cm": 34
    },
    "heat_sources": [],
    "induction_compatible": false
  },
  {
    "handle": "rekha-laser-marked-chai-bowl",
    "title": "Rekhā Laser-Marked Chai Bowl",
    "sku": "MT-TER-BWL-220",
    "vendor": "Maison Tavo",
    "product_category": "Home & Garden > Kitchen & Dining > Tableware > Drinkware > Mugs",
    "product_type": "Tea bowl",
    "tags": [
      "Terre Clay",
      "Chai Bowl",
      "Laser Marked",
      "Ceramic",
      "Hospitality",
      "Personalisation",
      "Concept Spec"
    ],
    "lineup": "Terre Clay",
    "status": "draft",
    "claim_status": "CONCEPT_SPEC",
    "reference_class": "personalised hospitality drinkware",
    "concept_thesis": "Create permanent, serialisable decoration without decals.",
    "material_architecture": "High-fired stoneware cup; glazed interior; controlled exterior marking band.",
    "food_contact_strategy": "Interior remains unmarked glaze; exterior mark must not undermine lip or grip.",
    "fabrication_route": "Laser-test cylindrical coupons using rotary fixture and dynamic focus; mark after glaze only if crack-free.",
    "interaction_performance_intent": "220 ml handleless cup; exterior traceability and venue edition layer.",
    "care_hypothesis": "Hand wash initial prototype; dishwasher after cycle validation.",
    "engineering_risks": [
      "Curved-focus variation",
      "micro-cracking",
      "mark roughness",
      "code readability after washing."
    ],
    "required_prototype_tests": [
      "Microscopy",
      "thermal cycling",
      "code scan after 500 washes",
      "stain and abrasion."
    ],
    "agent_intents": [
      "personalised chai bowl",
      "laser-marked cup",
      "hospitality edition"
    ],
    "negative_constraints": [
      "microwave/dishwasher claims before testing"
    ],
    "benchmark_logic": "Permanent ceramic marking supports serialisation, but the decorative process itself is not the safety proof.",
    "sources": [
      "R01",
      "R02",
      "R04"
    ],
    "description_html": "<p>A 220 ml tea bowl with a narrow laser-marked band that behaves like a material watermark rather than applied decoration.</p><h3>Etched register</h3><p>A 12 mm exterior band carries repeated linear notation, batch index and an optional machine-readable serial. The interior remains smooth and fully glazed.</p><h3>Hospitality detail</h3><p>The foot is recessed so the bowl can be carried on a small metal service tray without the pattern contacting the table.</p><h3>Personalisation</h3><p>The same geometry can support venue editions or room-number sets without changing the clay tool.</p><p><strong>Concept-spec notice:</strong> This is a concept listing. Laser process, glaze contrast, QR readability, thermal shock and commercial washing are not certified.</p>",
    "seo_title": "Rekhā Laser-Marked Chai Bowl | Maison Tavo",
    "seo_description": "A high-fired 220 ml chai bowl concept with a laser-marked exterior register for hospitality editions and provenance.",
    "price_usd": 42,
    "weight_grams": 230,
    "variant_option": {
      "name": "Capacity",
      "value": "220 ml"
    },
    "dimensions": {
      "capacity_ml": 220
    },
    "heat_sources": [],
    "induction_compatible": false
  },
  {
    "handle": "forge-relay-dual-mass-skillet",
    "title": "Forge Relay Dual-Mass Skillet",
    "sku": "MT-FOR-RLY-26",
    "vendor": "Maison Tavo",
    "product_category": "Home & Garden > Kitchen & Dining > Cookware & Bakeware > Cookware > Skillets & Frying Pans > Skillets",
    "product_type": "Skillet",
    "tags": [
      "Forge Hybrid",
      "Skillet",
      "Carbon Steel",
      "Bronze",
      "Modular",
      "Induction",
      "Hospitality",
      "Concept Spec"
    ],
    "lineup": "Forge Hybrid",
    "status": "draft",
    "claim_status": "CONCEPT_SPEC",
    "reference_class": "modular mixed-metal cookware",
    "concept_thesis": "Switch between fast response and thermal mass through a removable component.",
    "material_architecture": "Thin nitrided carbon-steel vessel + removable non-food-contact bronze thermal ring + steel handle.",
    "food_contact_strategy": "Carbon steel is intended food-contact surface; ring must remain external.",
    "fabrication_route": "Deep-draw/spin carbon body; nitride or season; cast/machine ring; positive mechanical lock with cold-state removal only.",
    "interaction_performance_intent": "Direct induction/gas pan; 26 cm general searing; ring supports table retention.",
    "care_hypothesis": "Hand wash; dry and oil steel; remove ring before washing.",
    "engineering_risks": [
      "Ring movement",
      "burn hazard",
      "galvanic contact",
      "trapped moisture",
      "induction coupling change."
    ],
    "required_prototype_tests": [
      "Hob response",
      "ring retention",
      "handle temperature",
      "thermal map",
      "corrosion",
      "drop",
      "1000 attach cycles."
    ],
    "agent_intents": [
      "modular skillet",
      "high-heat searing",
      "table-service pan",
      "mixed-metal cookware"
    ],
    "negative_constraints": [
      "dishwasher safe",
      "remove ring hot",
      "nonstick coating"
    ],
    "benchmark_logic": "Made In separates materials by task; this concept extends that logic inside one reconfigurable product.",
    "sources": [
      "R01",
      "R02",
      "R03"
    ],
    "description_html": "<p>A lightweight searing pan that uses two material behaviours instead of forcing one metal to perform every job.</p><h3>Working body</h3><p>A thin nitrided carbon-steel bowl provides direct, responsive searing and a seasoning-capable cooking surface.</p><h3>Thermal ring</h3><p>A removable cast-bronze outer ring seats around the lower wall as a heat reservoir and tabletop trivet. Removing it restores a lighter line-cook mode; fitting it slows temperature loss for table service.</p><h3>System logic</h3><p>The ring is not represented as a permanent bonded layer. Keeping it mechanically separate makes cleanability, repair and contradictory thermal behaviours explicit.</p><p><strong>Concept-spec notice:</strong> Nitriding, bronze alloy, fit tolerance, hot handling, induction behaviour and food-contact boundary require engineering validation.</p>",
    "seo_title": "Forge Relay Dual-Mass Skillet | Maison Tavo",
    "seo_description": "A modular 26 cm carbon-steel skillet concept with a removable bronze thermal ring for cookline and table modes.",
    "price_usd": 320,
    "weight_grams": 2100,
    "variant_option": {
      "name": "Diameter",
      "value": "26 cm"
    },
    "dimensions": {
      "diameter_cm": 26
    },
    "heat_sources": [
      "induction",
      "gas"
    ],
    "induction_compatible": true
  },
  {
    "handle": "forge-split-field-plancha",
    "title": "Forge Split-Field Plancha",
    "sku": "MT-FOR-PLN-46",
    "vendor": "Maison Tavo",
    "product_category": "Home & Garden > Kitchen & Dining > Cookware & Bakeware > Cookware > Griddles & Grill Pans",
    "product_type": "Griddle",
    "tags": [
      "Forge Hybrid",
      "Plancha",
      "Carbon Steel",
      "Bronze",
      "Stainless Steel",
      "Hospitality",
      "Concept Spec"
    ],
    "lineup": "Forge Hybrid",
    "status": "draft",
    "claim_status": "CONCEPT_SPEC",
    "reference_class": "split-function cookware",
    "concept_thesis": "Map material to task across one product: sear, rest and serve.",
    "material_architecture": "Nitrided carbon-steel griddle + cast-bronze service mass + removable stainless food tray.",
    "food_contact_strategy": "Steel griddle and stainless tray contact food; bronze does not.",
    "fabrication_route": "Laser-cut/form steel; cast/machine bronze block; sliding expansion joint; drawn stainless tray.",
    "interaction_performance_intent": "Twin-burner use; restaurant tableside workflow; separate raw/cooked zones by removable tray.",
    "care_hypothesis": "Disassemble; hand wash steel; tray dishwasher target pending.",
    "engineering_risks": [
      "Warping",
      "differential expansion",
      "cross-contamination",
      "weight",
      "hot handles",
      "uneven induction."
    ],
    "required_prototype_tests": [
      "Flatness thermal cycle",
      "two-zone mapping",
      "load deflection",
      "tray cleanability",
      "lift ergonomics."
    ],
    "agent_intents": [
      "plancha",
      "twin burner",
      "tableside searing",
      "mixed material griddle"
    ],
    "negative_constraints": [
      "single-burner",
      "dishwasher-safe assembly",
      "direct bronze food contact"
    ],
    "benchmark_logic": "Inspired by material-specialist ranges, but differentiated through spatially assigned material functions.",
    "sources": [
      "R01",
      "R02",
      "R03"
    ],
    "description_html": "<p>A plancha concept that physically divides two cooking materials across one continuous service object.</p><h3>Steel zone</h3><p>Two-thirds of the surface is nitrided carbon steel for high-heat searing, browning and scraping.</p><h3>Bronze service zone</h3><p>A raised cast-bronze end platform is thermally coupled but isolated from direct food contact by a removable stainless tray. It holds cooked items, sauces or garnishes while the steel zone remains active.</p><h3>Hospitality choreography</h3><p>The pan moves from twin-burner cooking to tableside finishing without becoming a decorative serving board disconnected from the cooking process.</p><p><strong>Concept-spec notice:</strong> This speculative assembly requires validation for differential expansion, flatness, safe lifting, induction coverage and removable-tray hygiene.</p>",
    "seo_title": "Forge Split-Field Plancha | Maison Tavo",
    "seo_description": "A twin-burner mixed-material plancha concept separating active carbon-steel searing from a stainless-lined bronze service zone.",
    "price_usd": 480,
    "weight_grams": 4900,
    "variant_option": {
      "name": "Size",
      "value": "46 × 28 cm"
    },
    "dimensions": {
      "length_cm": 46,
      "width_cm": 28
    },
    "heat_sources": [
      "gas"
    ],
    "induction_compatible": false
  },
  {
    "handle": "forge-terre-nested-roaster",
    "title": "Forge–Terre Nested Roaster",
    "sku": "MT-HYB-RST-34",
    "vendor": "Maison Tavo",
    "product_category": "Home & Garden > Kitchen & Dining > Cookware & Bakeware > Bakeware > Roasting Pans",
    "product_type": "Roasting pan",
    "tags": [
      "Forge Hybrid",
      "Terre Clay",
      "Roaster",
      "Stainless Clad",
      "Ceramic Cradle",
      "Induction",
      "Concept Spec"
    ],
    "lineup": "Forge × Terre",
    "status": "draft",
    "claim_status": "CONCEPT_SPEC",
    "reference_class": "nested oven-to-table cookware",
    "concept_thesis": "Separate thermal cooking performance from tactile table presentation.",
    "material_architecture": "Fully-clad stainless roasting insert + non-hob ceramic cradle + insulating contact points.",
    "food_contact_strategy": "Stainless insert contacts food; cradle is support only.",
    "fabrication_route": "Form clad insert; high-fire cradle to tolerance; laser mark exterior; create drainage and lift clearances.",
    "interaction_performance_intent": "Oven roast, deglaze insert on induction, dock at table.",
    "care_hypothesis": "Insert dishwasher target; cradle hand wash; never heat empty cradle on hob.",
    "engineering_risks": [
      "Tolerance drift",
      "hot insertion shock",
      "trapped grease",
      "user places cradle on hob",
      "weight."
    ],
    "required_prototype_tests": [
      "Docking thermal shock",
      "500 dock cycles",
      "spill drainage",
      "induction insert flatness",
      "drop and lift."
    ],
    "agent_intents": [
      "oven-to-table roaster",
      "removable insert",
      "mixed-material serveware"
    ],
    "negative_constraints": [
      "ceramic cradle on hob",
      "monolithic cookware",
      "microwave use"
    ],
    "benchmark_logic": "Expands Made In’s cookware-to-tabletop breadth by making the interface itself the product thesis.",
    "sources": [
      "R01",
      "R02",
      "R03"
    ],
    "description_html": "<p>A low roasting vessel built as a stainless cooking tray nested inside an earthenware presentation cradle.</p><h3>Metal insert</h3><p>A removable fully-clad stainless insert performs oven roasting, deglazing and induction-compatible sauce finishing.</p><h3>Clay cradle</h3><p>A laser-marked high-fired ceramic cradle receives the hot insert at the table, protecting surfaces and converting cookware into a composed serving object.</p><h3>Replacement logic</h3><p>Either component can be replaced independently. The clay piece never goes on the hob and the metal insert can be cleaned without soaking the ceramic body.</p><p><strong>Concept-spec notice:</strong> The ceramic cradle is not cookware. Clear thermal, dimensional and misuse constraints must be validated and encoded.</p>",
    "seo_title": "Forge–Terre Nested Roaster | Maison Tavo",
    "seo_description": "A removable stainless roasting insert with a laser-marked ceramic presentation cradle for oven-to-table hospitality service.",
    "price_usd": 390,
    "weight_grams": 4200,
    "variant_option": {
      "name": "Size",
      "value": "34 × 24 cm"
    },
    "dimensions": {
      "length_cm": 34,
      "width_cm": 24
    },
    "heat_sources": [
      "oven",
      "induction"
    ],
    "induction_compatible": true
  },
  {
    "handle": "kuro-strip-200-chefs-knife",
    "title": "Kuro Strip 200 Chef's Knife",
    "sku": "MT-KUR-STR-200",
    "vendor": "Maison Tavo",
    "product_category": "Home & Garden > Kitchen & Dining > Kitchen Tools & Utensils > Kitchen Knives > Chef's Knives",
    "product_type": "Chef's knife",
    "tags": [
      "Kuro Strip",
      "Chef Knife",
      "Metal Strip",
      "Plain Edge",
      "Hospitality",
      "Concept Spec"
    ],
    "lineup": "Kuro Strip",
    "status": "draft",
    "claim_status": "CONCEPT_SPEC",
    "reference_class": "integral metal-frame knife",
    "concept_thesis": "Turn full-tang logic into a visible continuous structural strip.",
    "material_architecture": "Single nitrogen-treated stainless or alternative steel strip target + removable high-temperature grip sleeve.",
    "food_contact_strategy": "Blade is food contact; open frame must not create inaccessible soil traps.",
    "fabrication_route": "Laser-cut blank; forge/grind blade zone; bend/form handle loop if metallurgy permits; heat treat; finish; sleeve mould.",
    "interaction_performance_intent": "Thin 200 mm blade; neutral pinch grip; replaceable sleeve; no decorative Damascus dependency.",
    "care_hypothesis": "Hand wash; remove sleeve only for deep service per final design.",
    "engineering_risks": [
      "Handle fatigue",
      "edge hardness vs bendability conflict",
      "soil traps",
      "hot/cold feel",
      "balance."
    ],
    "required_prototype_tests": [
      "FEA and bend fatigue",
      "torque",
      "balance",
      "grip slip",
      "cleanability",
      "edge retention",
      "corrosion."
    ],
    "agent_intents": [
      "thin chef knife",
      "all-metal knife",
      "replaceable grip",
      "precision prep"
    ],
    "negative_constraints": [
      "bones",
      "frozen food",
      "dishwasher before validation"
    ],
    "benchmark_logic": "Made In uses single-rod full-tang forging; this reframes continuity as an exposed strip architecture rather than hidden tang construction.",
    "sources": [
      "R01",
      "R02",
      "R03"
    ],
    "description_html": "<p>A thin 20 cm chef knife concept formed from a single continuous strip of steel, with the handle architecture exposed rather than hidden under scales.</p><h3>One material path</h3><p>A laser-cut and forged strip runs from tip through heel, spine and open handle loop. The loop creates a visible counter-curve and keeps the knife unmistakably metal rather than imitating a conventional riveted handle.</p><h3>Grip interface</h3><p>A removable textured sleeve clips onto the lower handle rail while the spine rail stays exposed for visual continuity. Sleeve geometry, balance and fatigue are treated as service parts.</p><h3>Blade intent</h3><p>A thin, plain-edge blade targets precise push and draw cuts. It is not positioned for bones, frozen food or twisting loads.</p><p><strong>Concept-spec notice:</strong> Steel grade, heat treatment, distal taper, weld-free feasibility, balance, fatigue and sanitation require prototyping.</p>",
    "seo_title": "Kuro Strip 200 Chef's Knife | Maison Tavo",
    "seo_description": "A thin 200 mm chef knife concept shaped from one continuous metal strip with a replaceable grip sleeve.",
    "price_usd": 260,
    "weight_grams": 205,
    "variant_option": {
      "name": "Blade length",
      "value": "200 mm"
    },
    "dimensions": {
      "length_cm": 20
    },
    "heat_sources": [],
    "induction_compatible": false
  },
  {
    "handle": "kuro-trace-180-hybrid-edge-knife",
    "title": "Kuro Trace 180 Hybrid-Edge Knife",
    "sku": "MT-KUR-TRC-180",
    "vendor": "Maison Tavo",
    "product_category": "Home & Garden > Kitchen & Dining > Kitchen Tools & Utensils > Kitchen Knives > Chef's Knives",
    "product_type": "Hybrid-edge chef knife",
    "tags": [
      "Kuro Strip",
      "Chef Knife",
      "Serrated",
      "Micro Scalloped",
      "Thin Blade",
      "Hospitality",
      "Concept Spec"
    ],
    "lineup": "Kuro Strip",
    "status": "draft",
    "claim_status": "CONCEPT_SPEC",
    "reference_class": "hybrid-edge chef-format knife",
    "concept_thesis": "Combine skin-gripping serration with a sharpenable board-contact heel.",
    "material_architecture": "Thin high-carbon stainless blade target; 120 mm shallow micro-scalloped field + 60 mm plain heel + continuous metal strip handle.",
    "food_contact_strategy": "Blade contact only; serrations must be cleanable and corrosion-resistant.",
    "fabrication_route": "Laser-cut/forged blank; grind distal taper; CNC or wheel-grind repeatable scallops; deburr and passivate; removable grip sleeve.",
    "interaction_performance_intent": "Tomatoes, citrus, sandwiches, pastry and boneless proteins; limited chopping at heel.",
    "care_hypothesis": "Hand wash; specialist serration service; plain heel whetstone-compatible.",
    "engineering_risks": [
      "Steering in cut",
      "difficult sharpening",
      "fragile teeth",
      "poor rocking transition",
      "handed bias."
    ],
    "required_prototype_tests": [
      "Cut-force comparison",
      "slice deviation",
      "10k-cycle edge retention",
      "serration cleaning",
      "resharpen trial",
      "user ergonomics."
    ],
    "agent_intents": [
      "serrated chef knife",
      "tomato knife",
      "hybrid edge",
      "thin slicer"
    ],
    "negative_constraints": [
      "bone",
      "frozen food",
      "heavy rocking",
      "universal never-sharpen claim"
    ],
    "benchmark_logic": "Professional serrated cook knives exist, but the hybrid edge should be positioned as a specialised chef-format slicer, not an all-purpose replacement.",
    "sources": [
      "R01",
      "R02",
      "R06"
    ],
    "description_html": "<p>A thin 180 mm chef-format slicer with fine scallops limited to the forward two-thirds of the edge, leaving a plain heel for board contact and controlled chopping.</p><h3>Serrated field</h3><p>Shallow, widely spaced micro-scallops are proposed for tomatoes, citrus, pastry and soft-skinned produce. This is not a bread-knife saw profile.</p><h3>Plain heel</h3><p>The final 60 mm remains a conventional sharpenable edge for herbs, onions and close board work.</p><h3>Serviceable geometry</h3><p>The serration pitch, depth and handedness are explicit schema fields because they determine sharpening method and use suitability.</p><p><strong>Concept-spec notice:</strong> Edge geometry is a test target. The product must not claim universal chef-knife performance or “never needs sharpening” until abrasion and resharpening trials are complete.</p>",
    "seo_title": "Kuro Trace 180 Hybrid-Edge Knife | Maison Tavo",
    "seo_description": "A thin 180 mm chef-format knife concept combining a shallow micro-scalloped front edge with a plain working heel.",
    "price_usd": 230,
    "weight_grams": 178,
    "variant_option": {
      "name": "Blade length",
      "value": "180 mm"
    },
    "dimensions": {
      "length_cm": 18
    },
    "heat_sources": [],
    "induction_compatible": false
  },
  {
    "handle": "kuro-trace-150-micro-scalloped-utility-knife",
    "title": "Kuro Trace 150 Micro-Scalloped Utility Knife",
    "sku": "MT-KUR-UTL-150",
    "vendor": "Maison Tavo",
    "product_category": "Home & Garden > Kitchen & Dining > Kitchen Tools & Utensils > Kitchen Knives",
    "product_type": "Utility knife",
    "tags": [
      "Kuro Strip",
      "Utility Knife",
      "Micro Serrated",
      "Thin Blade",
      "Hospitality",
      "Concept Spec"
    ],
    "lineup": "Kuro Strip",
    "status": "draft",
    "claim_status": "CONCEPT_SPEC",
    "reference_class": "micro-scalloped utility knife",
    "concept_thesis": "Create low-force skin entry in a compact prep format.",
    "material_architecture": "Thin high-carbon stainless blade target + fine scallops + continuous strip frame + removable grip web.",
    "food_contact_strategy": "Stainless blade target; open frame and sleeve interface must be fully cleanable.",
    "fabrication_route": "Blank, heat treat, precision scallop grind, passivation, frame forming, removable sleeve.",
    "interaction_performance_intent": "Tomato, citrus, sandwich, pastry and cooked sausage slicing.",
    "care_hypothesis": "Hand wash; specialist sharpening.",
    "engineering_risks": [
      "Right/left bias",
      "tooth damage",
      "hard-to-sharpen edge",
      "crumb retention."
    ],
    "required_prototype_tests": [
      "Cut force",
      "steering",
      "hygiene swab",
      "abrasion",
      "regrind feasibility",
      "8-hour fatigue trial."
    ],
    "agent_intents": [
      "utility knife",
      "tomato knife",
      "breakfast station",
      "sandwich prep"
    ],
    "negative_constraints": [
      "bone",
      "frozen foods",
      "hard squash",
      "plain-edge chopping"
    ],
    "benchmark_logic": "Serrated utility knives are an established reference class; differentiation lies in exposed strip construction and hospitality-specific data.",
    "sources": [
      "R01",
      "R02",
      "R07"
    ],
    "description_html": "<p>A narrow 150 mm utility blade that treats micro-serration as a precision skin-breaking geometry rather than an aggressive saw.</p><h3>Fine scallops</h3><p>A shallow single-sided micro-scallop pattern is proposed for ripe tomatoes, citrus, sausages and sandwich assembly.</p><h3>Strip handle</h3><p>The exposed continuous-metal frame carries a removable grip web, reducing permanent mixed-material joints.</p><h3>Hospitality role</h3><p>Compact reach and low blade height suit garde-manger, breakfast and pass stations where large chef knives are excessive.</p><p><strong>Concept-spec notice:</strong> Handedness, scallop geometry, sharpening, edge life and commercial sanitation remain test items.</p>",
    "seo_title": "Kuro Trace 150 Utility Knife | Maison Tavo",
    "seo_description": "A thin 150 mm micro-scalloped utility knife concept for soft-skinned produce, sandwiches and compact hospitality prep.",
    "price_usd": 175,
    "weight_grams": 126,
    "variant_option": {
      "name": "Blade length",
      "value": "150 mm"
    },
    "dimensions": {
      "length_cm": 15
    },
    "heat_sources": [],
    "induction_compatible": false
  },
  {
    "handle": "forge-terre-service-tongs",
    "title": "Forge–Terre Service Tongs",
    "sku": "MT-HYB-TNG-24",
    "vendor": "Maison Tavo",
    "product_category": "Home & Garden > Kitchen & Dining > Kitchen Tools & Utensils > Tongs",
    "product_type": "Serving tongs",
    "tags": [
      "Forge Hybrid",
      "Terre Clay",
      "Tongs",
      "Spring Steel",
      "Ceramic",
      "Hospitality",
      "Concept Spec"
    ],
    "lineup": "Forge × Terre",
    "status": "draft",
    "claim_status": "CONCEPT_SPEC",
    "reference_class": "mixed-material serving utensil",
    "concept_thesis": "Put resilient metal at the food interface and expressive clay at the hand interface.",
    "material_architecture": "Continuous spring steel body + removable high-fired ceramic thumb pads.",
    "food_contact_strategy": "Steel tips contact food; pads remain outside contact zone.",
    "fabrication_route": "Laser-cut/bend spring strip; high-fire pad pair; mechanical snap carrier; exterior laser marking.",
    "interaction_performance_intent": "Bread, pastry and garnish service; 24 cm table scale.",
    "care_hypothesis": "Remove pads for cleaning until washability validated.",
    "engineering_risks": [
      "Pad chip",
      "detachment",
      "crevice soil",
      "spring fatigue",
      "thermal transfer."
    ],
    "required_prototype_tests": [
      "100k flex cycles",
      "pad drop",
      "retention",
      "commercial wash",
      "food soil swab."
    ],
    "agent_intents": [
      "serving tongs",
      "pastry tongs",
      "mixed-material utensil"
    ],
    "negative_constraints": [
      "grill use",
      "heavy lifting",
      "dishwasher claim"
    ],
    "benchmark_logic": "Extends a material-specialist catalogue into small tools while keeping each material’s function explicit.",
    "sources": [
      "R01",
      "R02",
      "R03"
    ],
    "description_html": "<p>A pair of service tongs using spring steel for force and removable fired-clay thumb pads for thermal tactility and table presentation.</p><h3>Metal skeleton</h3><p>A continuous spring-steel strip supplies flex, alignment and cleanable food-contact tips.</p><h3>Clay interfaces</h3><p>Laser-marked ceramic pads clip onto the handle zone only, staying clear of food and allowing replacement after chips.</p><h3>Use case</h3><p>Designed for bread, pastry and plated garnish service rather than high-force grill work.</p><p><strong>Concept-spec notice:</strong> Pad retention, chip containment, wash cycles and spring fatigue must be tested before hospitality use.</p>",
    "seo_title": "Forge–Terre Service Tongs | Maison Tavo",
    "seo_description": "A 24 cm spring-steel serving tong concept with removable laser-marked ceramic grip pads.",
    "price_usd": 78,
    "weight_grams": 210,
    "variant_option": {
      "name": "Length",
      "value": "24 cm"
    },
    "dimensions": {
      "length_cm": 24
    },
    "heat_sources": [],
    "induction_compatible": false
  }
];
