const themeRoot = `${import.meta.dir}/..`;
const banner = '/* Generated by bun run build in theme/. Source: scripts/src. Do not edit. */';

const jobs = [
  {
    entry: `${themeRoot}/scripts/src/maison-runtime.js`,
    outfile: `${themeRoot}/assets/maison-runtime.js`,
  },
  {
    entry: `${themeRoot}/scripts/src/lookbook.js`,
    outfile: `${themeRoot}/assets/microapp-lookbook.js`,
  },
];

for (const job of jobs) {
  const proc = Bun.spawnSync({
    cmd: [
      'bun',
      'build',
      job.entry,
      `--outfile=${job.outfile}`,
      '--minify',
      '--target=browser',
      '--format=iife',
      `--banner=${banner}`,
    ],
    cwd: themeRoot,
    stdout: 'inherit',
    stderr: 'inherit',
  });

  if (proc.exitCode !== 0) {
    console.error(`Failed to bundle ${job.entry}`);
    process.exit(proc.exitCode ?? 1);
  }
}

console.log('Bundled theme assets: maison-runtime.js, microapp-lookbook.js');
